# Generated by Django 4.1.4 on 2023-11-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=25)),
                ("secondname", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=25)),
                ("phone", models.IntegerField()),
            ],
            options={
                "db_table": "studetails",
            },
        ),
    ]
